backend_airspress/airspress/account/urls.py
from django.conf.urls import patterns, url

from account import views

urlpatterns = patterns('',

    url(r'^mytrips/add/$', views.addTrip, name='addtrip'),
    url(r'^mytrips/requested_trips/$', views.requestedTrips, name='myRequest'),
    url(ur'^edit/(?P<section>.*)/$', views.edit_profile, name='edit_profile'),
    url(ur'^inbox/$', views.inbox,name='inbox'),
    url(ur'^talk/(?P<key>.*)/$', views.instant_messaging,name='talk'),
    url(ur'^referral/$', views.referral,name='referral'),
    url(ur'^usersRequest/$', views.otRequests, name='otRequest'),
    url(ur'^(?P<key>.*)/trips/$', views.myTrips, name='myTrip'),
    url(ur'^(?P<key>.*)/deals/confirm_delivery/$', views.confirm_delivery, name='confirm_delivery'),
    url(ur'^(?P<key>.*)/deals/confirm_payment/$', views.confirm_payment, name='confirm_payment'),
    url(ur'^(?P<key>.*)/deals/review/$', views.reviewTrip, name='make_review'),
    url(ur'^(?P<key>.*)/deals/accept/$', views.accept_request, name='accept_request'),
    url(ur'^(?P<key>.*)/deals/$', views.deals, name='deals'),
    url(ur'^(?P<key>.*)/$', views.profileView, name='profile'),
    #url(r'^search', views.searchTrips, name='search'),
    
   )

backend_airspress/airspress/airspress/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
import views
from django.conf.urls.i18n import i18n_patterns

admin.autodiscover()


urlpatterns = patterns('', 
    url(r'session_security/', include('session_security.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('signup.urls',namespace='signup')),
    url(r'^trips/', include('trips.urls',namespace='trips')),
    url(r'^account/', include('account.urls',namespace='account')),
    url(r'^payment/', include('asp_payment.urls',namespace='payment')),
    url(r'^contact/',views.contact, name='contact'),
    )
urlpatterns += i18n_patterns('',
    # Examples:
    #url(r'^$', 'airspress.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('signup.urls',namespace='signup')),
    url(r'^trips/', include('trips.urls',namespace='trips')),
    url(r'^account/', include('account.urls',namespace='account')),
    url(r'^payment/', include('asp_payment.urls',namespace='payment')),
    url(r'^contact/',views.contact, name='contact'),
    url(r'^faq/',views.faq, name='faq'),
    url(r'^about/',views.about, name='about'),
    url(r'^terms/',views.terms, name='terms'),
    )
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()

backend_airspress/airspress/trips/urls.py
from django.conf.urls import patterns, url

from trips import views

urlpatterns = patterns('',
##    url(r'^$', views.IndexView.as_view(), name='index'),
##    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
##    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
##    url(r'^(?P<poll_id>\d+)/votes/$', views.votes, name='votes'),
    url(r'^$', views.activeTrips, name='index'),
    url(r'^search', views.searchTrips, name='search'),
    url(ur'^(?P<key>.*)/request/$', views.requestTrip, name='request'),
   )

backend_airspress/airspress/trips/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from airspress import settings

class searchForm(forms.Form):
    depDate1 = forms.DateField(required=False, input_formats=settings.DATE_INPUT_FORMATS)
    depDate2 = forms.DateField(required=False, input_formats=settings.DATE_INPUT_FORMATS)
    cityDep = forms.CharField(required=False)
    cityArr = forms.CharField(required=False)

class addForm(forms.Form):
    # first trip
    depDate = forms.DateField( input_formats=settings.DATE_INPUT_FORMATS)
    arrivDate = forms.DateField( input_formats=settings.DATE_INPUT_FORMATS, required=False)
    weightGood = forms.IntegerField()
    # backtrip
    depDate2 = forms.DateField( input_formats=settings.DATE_INPUT_FORMATS, required=False)
    arrivDate2 = forms.DateField( input_formats=settings.DATE_INPUT_FORMATS, required=False)
    weightGood2 = forms.IntegerField(required=False)
    return_check = forms.BooleanField(required=False)
    # all
    cityDep = forms.CharField()
    cityArr = forms.CharField()
    # distance between places
    distance = forms.DecimalField(required=False)
    unit_price = forms.DecimalField()
    custom_price = forms.DecimalField(required=False)
    def clean(self):
        cleaned_data = super(addForm, self).clean()
        is_coming_back = cleaned_data.get('return_check')
        depart = cleaned_data.get('depDate2')
        weight = cleaned_data.get('weightGood2')
        if is_coming_back:
            msg = _('This field is required because you have roundtrip option selected')
            if not depart:
                self._errors['depDate2'] =  self.error_class([msg])
            if not weight:
                self._errors['weightGood2'] = self.error_class([msg])
        return cleaned_data
        
class requestForm(forms.Form):
    item_name = forms.CharField()
    item_price = forms.DecimalField()
    item_quantity = forms.IntegerField()
    shop_name = forms.CharField()
    weightGood = forms.IntegerField()
    comments = forms.CharField(required=False)
    dimensions_1 = forms.IntegerField(required=False)
    dimensions_2 = forms.IntegerField(required=False)
    dimensions_3 = forms.IntegerField(required=False)
    request1 = forms.BooleanField(required=False)
    request2 = forms.BooleanField(required=False)
    
    def clean(self):
        cleaned_data = super(requestForm, self).clean()
        price = cleaned_data.get('item_price')
        name = cleaned_data.get('item_name')
        quantity = cleaned_data.get('quantity')
        shop = cleaned_data.get('shop_name')
        weight = cleaned_data.get('weightGood')
        comment = cleaned_data.get('comments')
        msg = 'Error'
        if not (weight or name or quantity):
            self._errors['request1'] = self.error_class([msg])
        elif not(price or comment or shop):
            self._errors['request2'] = self.error_class([msg]) 
        return cleaned_data
    
class editproForm(forms.Form):
    paypalMail = forms.EmailField()
    userBio = forms.CharField()
    timeZone = forms.CharField()
    profilePic = forms.FileField(label=_('Select a picture'), help_text ='max. 2mb' )

class reviewForm(forms.Form):
    text = forms.CharField(max_length=200)
    rating= forms.DecimalField()
    def clean_rating(self):
        data = self.cleaned_data['rating']
        return str(data)

backend_airspress/airspress/trips/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.core.urlresolvers import reverse
from signup.schemes import User #ParseUser
from trips.crtrips import trip, tripFind, tripRequest
from signup.schemes import is_logged_in
from trips.forms import searchForm, requestForm
from string import split
from account.actions import get_profile_pic, notify
from django.utils import timezone
from parse_rest.query import QueryResourceDoesNotExist

def fbPicture(request):
    try:
        pPicture = request.session['pPicture']
    except:
        pPicture=''
    return pPicture
def activeTrips(request):
    cUser = is_logged_in(request)
    if cUser:
        allTrips = trip.Query.filter(departureDate__gte=timezone.now()).order_by("departureDate")
        page_one = allTrips.limit(25)
        k = 0
        tripDict = {}
        for anyTrip in page_one :
            k = k + 1
            pub_date = ''
            travelerUser = ''
            departDate = ''
            destLocation = ''
            oriLocation = ''
            travelerId = False
            tripId = ''
            available_weight = 0
            total_weight = 0
            user_rating = 0
            pPicture=''
            try:
                pub_date = anyTrip.createdAt
                travelerId  = anyTrip.traveler.objectId
                departDate = anyTrip.departureDate.date()
                destLocation = anyTrip.toLocation
                oriLocation = anyTrip.fromLocation
                tripId = anyTrip.objectId
                pPicture = get_profile_pic(travelerId)
                available_weight = anyTrip.availCapacity
                total_weight = anyTrip.totalCapacity
                traveler = User.Query.get(objectId=travelerId)
                unit_price = anyTrip.unitPriceUsd
                user_rating = traveler.userRating
            except (AttributeError, QueryResourceDoesNotExist):
                pass
            
            if travelerId:#use travelerId to access traveler info
                travelerUser = ''
                try:
                    travelerUser = User.Query.get(objectId=travelerId).username
                except (AttributeError, QueryResourceDoesNotExist):
                    pass
                if travelerUser == '':
                    pass
                else:
                    areas_ori_location = split(oriLocation,',') 
                    areas_dest_location = split(destLocation,',')
                    destCountry = areas_dest_location[-1]
                    destCity = areas_dest_location[0]
                    oriCountry = areas_ori_location[-1]
                    oriCity = areas_ori_location[0]
                    tripDict['objTrip'+str(k)] = {'pub_date':pub_date, 
                                'travelerUser':travelerUser, 'travelerRating':user_rating,
                                'departDate':{'month':departDate.strftime("%B"), 'day':departDate.day},
                                'destLocation':{'city':destCity,'country':destCountry}, 
                                'oriLocation':{'city':oriCity,'country':oriCountry}, 
                                'available':available_weight,'total':total_weight,
                                'unit_price':unit_price,'tripId':tripId, 'pPicture':pPicture,}
                    #once the context dict created we can use render()
                    
        #Preparing search form on page
        if request.method == 'POST':
            searchView = searchForm(request.POST)
            if searchView.is_valid():
                pass
            else:
                print searchView.errors
                
        else:
            searchView = searchForm()
        context_dict = {'tripDict':tripDict,'greetings':cUser.username, 
                        'myPicture':get_profile_pic(cUser.objectId),'searchForm':searchView}
       
            
        return render(request, 'trips/voyage.html', context_dict )
    return HttpResponseRedirect(reverse('signup:index'))

def searchTrips(request):
    '''
    Generate results page 
    or just a page that look like the 'activeTrips' one.
    '''
    tripDict={}
    cUser = is_logged_in(request)
    if cUser:
        myPicture = get_profile_pic(cUser.objectId)
        if request.method == 'POST': #If it's POST we'll output results no matter what, results could be errors
            searchView = searchForm(request.POST)
            if searchView.is_valid():
                tripDict = tripFind(request, cUser, searchView)
                
        #Preparing search form on page
            else:
                print searchView.errors
                
            context_dict = {'tripDict':tripDict,'greetings':cUser.username, 
                            'myPicture':get_profile_pic(cUser.objectId),'searchForm':searchView}
            
            
            return render(request, 'trips/voyage.html', context_dict )
        else:
            searchView = searchForm()
    else:
        HttpResponseRedirect(reverse('signup:index'))
            
    return HttpResponseRedirect(reverse('trips:index'))

def requestTrip(request, key):
    alert={}
    cUser = is_logged_in(request)
    if cUser:
        myPicture = get_profile_pic(cUser.objectId)
        if request.method == 'POST': #If it's POST we'll output results no matter what, results could be errors
            reqView = requestForm(request.POST)
            if reqView.is_valid():
                alert = tripRequest(cUser, reqView, key)
                # if alert is success, notify traveler;
                try:
                    if alert['type'] == 'success':
                        tripnow = trip.Query.get(objectId=key)
                        
                        notify(request, "new_request", cUser.Name, tripnow.traveler.Name, tripnow.traveler.objectId, tripnow.traveler.email)
                        
                except (KeyError,AttributeError):
                    pass
                print alert              
            else:
                print reqView.errors
            return render(request, 'trips/modals.html', {'key':key,'alert':alert,'greetings':cUser.username, 'requestForm':reqView, 'pPicture':myPicture})             
        else:
            reqView = requestForm()
    else:
        return HttpResponseRedirect(reverse('signup:index'))
    return render(request, 'trips/modals.html', {'key':key,'greetings':cUser.username, 'requestForm':reqView})

backend_airspress/airspress/trips/templates/trips/account_base.html
{% load i18n %}
{% load static from staticfiles %}
{% load compress %}
<!DOCTYPE html>
<html lang="en">
<head> 
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- all favicons -->
	<link rel="shortcut icon" href="{% static 'signup/img/favicons/favicon.ico' %}">
	<link rel="icon" sizes="16x16 32x32 64x64" href="{% static 'signup/img/favicons/favicon.ico' %}">
	<link rel="icon" type="image/png" sizes="196x196" href="{% static 'signup/img/favicons/favicon-192.png' %}">
	<link rel="icon" type="image/png" sizes="160x160" href="{% static 'signup/img/favicons/favicon-160.png' %}">
	<link rel="icon" type="image/png" sizes="96x96" href="{% static 'signup/img/favicons/favicon-96.png' %}">
	<link rel="icon" type="image/png" sizes="64x64" href="{% static 'signup/img/favicons/favicon-64.png' %}">
	<link rel="icon" type="image/png" sizes="32x32" href="{% static 'signup/img/favicons/favicon-32.png' %}">
	<link rel="icon" type="image/png" sizes="16x16" href="{% static 'signup/img/favicons/favicon-16.png' %}">
	<link rel="apple-touch-icon" href="{% static 'signup/img/favicons/favicon-57.png' %}">
	<link rel="apple-touch-icon" sizes="114x114" href="{% static 'signup/img/favicons/favicon-114.png' %}">
	<link rel="apple-touch-icon" sizes="72x72" href="{% static 'signup/img/favicons/favicon-72.png' %}">
	<link rel="apple-touch-icon" sizes="144x144" href="{% static 'signup/img/favicons/favicon-144.png' %}">
	<link rel="apple-touch-icon" sizes="60x60" href="{% static 'signup/img/favicons/favicon-60.png' %}">
	<link rel="apple-touch-icon" sizes="120x120" href="{% static 'signup/img/favicons/favicon-120.png' %}">
	<link rel="apple-touch-icon" sizes="76x76" href="{% static 'signup/img/favicons/favicon-76.png' %}">
	<link rel="apple-touch-icon" sizes="152x152" href="{% static 'signup/img/favicons/favicon-152.png' %}">
	<link rel="apple-touch-icon" sizes="180x180" href="{% static 'signup/img/favicons/favicon-180.png' %}">
	<meta name="msapplication-TileColor" content="#FFFFFF">
	<meta name="msapplication-TileImage" content="{% static 'signup/img/favicons/favicon-144.png' %}">
	<meta name="msapplication-config" content="{% static 'signup/img/favicons/browserconfig.xml' %}">
	<!-- all favicons END -->

	{% compress css %}
	<link rel="stylesheet" type="text/css" href="{% static 'signup/css/bootstrap.min.css' %}" />
	{% endcompress %}
	{% compress css %}
	<link rel="stylesheet" type="text/css" href="{% static 'account/css/flat-ui.min.css' %}" />
	{% endcompress %}
	{% compress css %}
	<link rel="stylesheet" type="text/css" href="{% static 'signup/css/font-awesome.min.css' %}" />
	{% endcompress %}
	{% compress css %}
	{% block stylesheet %} {% endblock stylesheet %}
	<link rel="stylesheet" type="text/css" href="{% static 'signup/css/custom-ui.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'signup/css/datepicker3.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'account/css/jquery.raty.css' %}">
	{% block stylesheet_bottom %} 	
	<!-- libraries -->
	<link rel="stylesheet" type="text/css" href="{% static 'account/css/libs/nanoscroller.css' %}" />

	<!-- global styles -->
	<link rel="stylesheet" type="text/css" href="{% static 'account/css/compiled/theme_styles.css' %}" />
	
	{% endblock stylesheet_bottom %}
	
	<link rel="stylesheet" type="text/css" href="{% static 'signup/css/custom.css' %}" />
	<!-- Footer Styles -->
    <link type="text/css" href="{% static 'signup/css/style.css' %}" rel="stylesheet"/>
	<!-- END Footer Styles -->
	{% endcompress %}
	{% block stylesheet_uncomp %}
	
	{% endblock stylesheet_uncomp %}
	
	{% block head_jscript_uncomp %}  {% endblock %}
	
	{% compress js %}
	{% block head_jscript %}  {% endblock %}
	{% endcompress %}
	
	
	<title> {% block title %} Airspress - A peer-to-peer delivery service{% endblock %} </title>
</head>

<body {% block onloader %} {% endblock %}>
<!-- Background image
<img id="bg-inline" src="/static/admin/img/bg-lg.png"></img> -->
<div id="theme-wrapper">
    <header style="background-color:#e82;" class="navbar" id="header-navbar">
			<div class="container">
				<a style="background-color:#e82; width:1.5em" href="/trips/" id="logo" class="navbar-brand">
					<img src="{% static 'signup/img/mini-logo.png' %}" alt="AirSpress" title="Ship for Cheap" style="display:flex;" class="hidden-sm normal-logo logo-white"/>
					
				</a>
				
				<div class="clearfix">
				<div style="margin-bottom: 0;" class="nav-no-collapse pull-right" id="header-nav">
					<ul style="margin-bottom: 0;" class="nav navbar-nav pull-right">
						<li>
							<a href="/trips/">
								<i class="fa fa-home"></i>&nbsp;{% trans "Home" %}
							</a>
						</li>
						<li>
							<a href="/faq/">
								<i class="fa fa-question-circle"></i>&nbsp;FAQ
							</a>
						</li>
						<li class="dropdown profile-dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<img src="{% firstof myPicture 'http://placehold.it/80&text=No+Image' %}" alt="" />
								<span class="hidden-xs">{{greetings}}</span> 
								{% if notifications.total %} <span class="label label-danger pull-right">{{notifications.total}}</span> {% endif %}
								<b class="caret"></b>
							</a>
							<ul class="dropdown-menu brand-color">
								
									<li><a href=" {% url 'account:profile' greetings %} ">{% trans "Profile" %} <span><i class="fa fa-cog pull-right"></i></span>
											
										</a>
									</li>
									<li><a href="{%  url 'account:otRequest' %}">{% trans "Incoming Requests" %}  
											<span class="label label-danger pull-right">{% firstof notifications.in_deals %}</span>
										</a>
									</li>
									<li><a href="{% url 'account:myTrip' greetings %}">{% trans "My Trips" %}
										</a>
									</li>
									<li>
										<a href="/account/mytrips/requested_trips/">{% trans "My Requests" %}
											<span class="label label-danger pull-right">{% firstof notifications.out_deals %}</span>
										</a>
									</li>
									<li><a href="/account/mytrips/add">{% trans "Add a trip" %}</a></li>
									<li><a href="{% url 'account:inbox' %}">{% trans "Inbox" %}
											<span class="label label-danger pull-right">{% firstof notifications.inbox %}</span>
										</a>
									</li>
									<li class='logout-btn'> 
									   <a href="/logout">  {% trans "Logout" %} <span class="glyphicon glyphicon-log-out pull-right"></span></a>
									</li>
								
							</ul>
						</li>
						<li class="hidden-xxs">
							<a href="/logout" class="btn">
								<i class="fa fa-power-off"></i>
							</a>
						</li>
					</ul>
				</div>
				</div>
			</div>
		</header>
		
        <!-- Page Content -->
        <div style="margin-left:0;" id="content-wrapper" class="{% block parent_class %} {% endblock parent_class %}">
            <div class="container-fluid">
			{% block content %}
                <div class="row">
				
                    <div class="col-lg-12">
                        
                    </div>
                </div>
			{% endblock %}
            </div>
			<hr class="prettyline">
        </div>
        <!-- /#page-content-wrapper -->
    </div>  <!-- /#wrapper -->
		<!-- Modal --> <div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"> 

					</div><!-- /.modal --> 
	

 	<footer>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <span class="copyright">Copyright © Airspress 2015</span>
					
                </div>
                <div class="col-md-4">
                    <ul class="list-inline social-buttons">
                        <li><a href="https://www.twitter.com/airspress" target="_blank"><i class="fa fa-twitter" ></i></a>
                        </li>
                        <li><a href="https://www.facebook.com/Airspress" target="_blank"><i class="fa fa-facebook"></i></a>
                        </li>
                        <li><a href="#" target="_blank"><i class="fa fa-linkedin"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline quicklinks">
                        <li><a href="/terms">{% trans "Terms of Use" %}</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.4.4/underscore-min.js"></script>
	<script type="text/javascript" src="{% static 'admin/js/JScustom.js' %}"></script>
	<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyAo_PT60oc_CGiUYJcI4gsYYa5UGZSBxp8&libraries=geometry,places&sensor=false&language=en-US"></script>

	<script type="text/javascript" src="{% static 'account/js/flat-ui.min.js' %}"></script>
	<script src="{% static 'signup/js/flowtype.js' %}"></script>
	<script type="text/javascript">
		$('body').flowtype({
			 minimum   : 250,
			 maximum   : 1200,
			 minFont   : 12,
			 maxFont   : 20,
			 fontRatio : 30
			});
	</script>
	
	{% include 'signup/session_security.html' %}
	
	<script type="text/javascript" src="{% static 'signup/js/bootstrap-datepicker.js' %}"></script>
	<script type="text/javascript" src="{% static 'account/js/jquery.raty.js' %}"></script>
	{% block datepicker %}
		<script> $('.datepicker').datepicker({
		  format: 'mm-dd-yyyy',
		  autoclose:true,
		  orientation: 'top'
		});
		</script>
	{% endblock datepicker %}
	
	{% block jscript %} 
	
		<!-- scripts -->
		<script src="{% static 'account/js/scripts.js' %}"></script>
		<script src="{% static 'account/js/pace.min.js' %}"></script>
	{% endblock jscript %}
	<script type="text/javascript" src="{% static 'signup/js/citySearch.js' %}"></script>
	<script type="text/javascript" src="{% static 'signup/js/currencySel.js' %}"></script>

	<script>
	 $(document).ready(function(){
  // $('#currency').on('change', updateCurrency);
  $('body').on('click', '.modal-trigger', displayModal);
  // $('body').on('click', '.deleter', deleteObject);
   $('body').on('submit', '#modal-form', saveForm);
   // alerts timeout
   window.setTimeout(function() {
    $(".alert-success").fadeTo(1500, 0).slideUp(500, function(){
        $(this).remove(); 
    });
}, 5000);
	window.setTimeout(function() {
    $("#notification-modal").fadeTo(1500, 0).slideUp(500, function(){
        $(this).modal('hide'); 
    });
}, 5000);

 });

 </script>

</body>
</html>

backend_airspress/airspress/trips/templates/trips/alerts.html
{% if alert %}
  <div class="alert alert-{{alert.type}} alert-dismissible">
    <button type="button" data-dismiss="alert" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <strong>{{ alert.text }} {{alert.message}}</strong> {% if alert.link %} <a href="{{alert.url}}">{{alert.link}}</a> {% endif %}
  </div>
{% endif %}

backend_airspress/airspress/trips/templates/trips/index.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'signup/bootstrap.min.css' %}" />
<!-- <link rel="stylesheet" type="text/css" href="{% static 'signup/custom.css' %}" /> -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="{% static 'signup/js/bootstrap.min.js' %}"></script>

<div class="container"> 
{% if greetings %}
<nav class="board-right"> 
<ul class="nav nav-pills nav-stacked"> 
	<li> <a href = "#">Home</a> </li>
	<li> <a href="#"> Profile</a> </li>
	<li class='logout-btn'> <a href="http://www.falconfake.com:8000/signup/logout">Logout</a> </li>
</ul>

</nav>
{% endif %}
    <hr class="prettyline">
    <br>
    <center>
	{% if greetings %}
    <h3> Hi, {{ greetings }}</h3>	
	{% endif %}
	{% if not greetings %}
    <h3> Request a delivery or Offer a delivery </h3>
	{% endif %}
    <br>
	{% if greetings %}
  <button class="btn btn-primary btn-lg" href="#signup" data-toggle="modal" data-target=".bs-modal-sm">Register a trip</button>
	{% else %}
	<button class="btn btn-primary btn-lg" href="#signup" data-toggle="modal" data-target=".bs-modal-sm">Sign Up</button>
	{% endif %}
  </center>
  <br>
    <hr class="prettyline">
 </div>
  
{% if not greetings %}
<!-- Modal -->
<div class="modal fade bs-modal-sm" id="myModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
        <br>
        <div class="bs-example bs-example-tabs">
            <ul id="myTab" class="nav nav-tabs">
              <li class="active"><a href="#signin" data-toggle="tab">Sign In</a></li>
            </ul>
        </div>
      <div class="modal-body">
        <div id="myTabContent" class="tab-content">
        <div class="tab-pane fade active in" id="signin">
            <fieldset>
            <!-- Sign In Button -->
            <div >
			<center>
              <label ></label>
              <div >
                <a href="login/fb" class="btn fb-signin btn-lg">Sign In with Facebook</a>
              </div>
            </div>
			<center>
            </fieldset>
            
        </div>
		</div>
	  </div>
	 </div>
	</div>
</div>
{% endif %}